//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baithuocdangian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noi_dung
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Mo_ta { get; set; }
        public Nullable<System.DateTime> Ngay_cap_nhat { get; set; }
        public string Noi_dung1 { get; set; }
        public string Anh_minh_hoa { get; set; }
        public Nullable<int> Thu_tu { get; set; }
        public Nullable<bool> Hien_thi { get; set; }
        public Nullable<int> Id_danhmuc { get; set; }
    
        public virtual tbl_Danhmuc tbl_Danhmuc { get; set; }
    }
}
