//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baithuocdangian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Danhmuc
    {
        public tbl_Danhmuc()
        {
            this.Noi_dung = new HashSet<Noi_dung>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Thu_tu { get; set; }
        public Nullable<bool> Hien_thi { get; set; }
        public string Mo_ta { get; set; }
    
        public virtual ICollection<Noi_dung> Noi_dung { get; set; }
    }
}
