//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baithuocdangian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Banner
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Duong_dan { get; set; }
        public string Link { get; set; }
        public Nullable<int> Thu_tu { get; set; }
        public Nullable<bool> Trang_thai { get; set; }
    }
}
